# Generated by Django 3.2.15 on 2022-09-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220913_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id_comment',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
