# Generated by Django 3.2.15 on 2022-09-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220920_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id_comment',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
