# Generated by Django 3.2.15 on 2022-09-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_id_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='id',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id_recipe',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
